export const AUTHENTICATION = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    SUCCESS_LOGIN_REQUEST : 'SUCCESS_LOGIN_REQUEST',
    REGISTRATION_REQUEST : 'REGISTRATION_REQUEST',
    SUCCESS_REGISTRATION_REQUEST : 'SUCCESS_REGISTRATION_REQUEST'
}