export const AUTHENTICATION = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    SUCCESS_LOGIN_REQUEST : 'SUCCESS_LOGIN_REQUEST',
    REGISTRATION_REQUEST : 'REGISTRATION_REQUEST',
    SUCCESS_REGISTRATION_REQUEST : 'SUCCESS_REGISTRATION_REQUEST'
}

export const DOCUMENT = {
    FETCH_DOCUMENTS : 'FETCH_DOCUMENTS',
    SUCCESS_FETCH_DOCUMENTS : 'SUCCESS_FETCH_DOCUMENTS',
    UPLOAD_DOCUMENT : 'UPLOAD_DOCUMENT',
    SUCCESS_UPLOAD_DOCUMENT : 'SUCCESS_UPLOAD_DOCUMENT',
    FETCH_ALL_DOCUMENTS : 'FETCH_ALL_DOCUMENTS',
    SUCCESS_FETCH_ALL_DOCUMENTS : 'SUCCESS_FETCH_ALL_DOCUMENTS',
    SET_PARSING_DOCUMENT : 'SET_PARSING_DOCUMENT'
}

export const USER_APPROVAL = {
    FETCH_INACTIVE_USERS : 'FETCH_INACTIVE_USERS',
    SUCCESS_FETCH_INACTIVE_USERS : 'SUCCESS_FETCH_INACTIVE_USERS',
    APPROVE_USER : 'APPROVE_USER',
    REJECT_USER: 'REJECT_USER'
}

export const ANALYSIS_REPORT = {
    UPLOAD_ANALYSIS : 'UPLOAD_ANALYSIS' 
}

export const DASHBORD_ACTIONS = {
    FETCH_DASHBOARD : 'FETCH_DASHBOARD',
    SUCCESS_FETCH_DASHBOARD : 'SUCCESS_FETCH_DASHBOARD'
}

export const PROFILE_ACTIONS = {
    FETCH_PROFILE : 'FETCH_PROFILE',
    SUCCESS_FETCH_PROFILE : 'SUCCESS_FETCH_PROFILE'
}