export const AUTHENTICATION = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    SUCCESS_LOGIN_REQUEST : 'SUCCESS_LOGIN_REQUEST',
    REGISTRATION_REQUEST : 'REGISTRATION_REQUEST',
    SUCCESS_REGISTRATION_REQUEST : 'SUCCESS_REGISTRATION_REQUEST'
}

export const DOCUMENT = {
    FETCH_DOCUMENTS : 'FETCH_DOCUMENTS',
    SUCCESS_FETCH_DOCUMENTS : 'SUCCESS_FETCH_DOCUMENTS',
    UPLOAD_DOCUMENT : 'UPLOAD_DOCUMENT',
    SUCCESS_UPLOAD_DOCUMENT : 'SUCCESS_UPLOAD_DOCUMENT'
}

export const USER_APPROVAL = {
    FETCH_INACTIVE_USERS : 'FETCH_INACTIVE_USERS',
    SUCCESS_FETCH_INACTIVE_USERS : 'SUCCESS_FETCH_INACTIVE_USERS',
    APPROVE_USER : 'APPROVE_USER',
}